apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu-deployment    
    aadpodidbinding: podidentity    # Set the label value to the selector defined in AzureIdentityBinding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curlpod
  template:
    metadata:
      labels:
        app: curlpod
    spec:
      containers:
      - name: workload-egress
        command:
        - sh
        - -c
        - while true; do sleep 1; done
        image: ubuntu                       # This is is supposed to install the minimal version of ubuntu
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "class-firewallrootca-cert"

