apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-2
  labels:
    app: app-deployment-2
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dotnetapp-v2
  template:
    metadata:
      labels:
        app: dotnetapp-v2
    spec:
      containers:
      - name: weatherconsole
        image: workloadcontainerregistry.azurecr.io/dotnetconsoleapp:ubuntuv1.1