apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
data:
  azurestorageaccountname: c3RhY2FjZXJ0c2hhcmU=
  azurestorageaccountkey: TWlDN3FsMFh5Y2l4N1RtazFDQjB2TEpQbEhtV0pXQW5sNDhrWjU5eHluaWZLTFVMUzR4NTlsNlpkcW1VcjFTY2hwV2pBUWdlbHZFU2ZzRkttSCtrN3c9PQ==