apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
data:
  azurestorageaccountname: <base64 encoded value of storage-acct name>
  azurestorageaccountkey: <base64 encoded value of storage-acct key>